---
# Main task: Load package installers, or not, based on tags.

- name: Load tasks dispatcher for ‘zoidy_ruby-vroom’
  include_role:
    name: zoidy_ruby-vroom
    tasks_from: all
  tags:
    - ruby-vroom
    - ruby-install-base
    - ruby-install-chruby
    - ruby-install-versions
    - ruby-rubygems-packages

